version: "2"
services:
  app:
    container_name: app
    image: pb10005/mondai-gallery
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    restart: always
    build: .
    ports:
      - "49160:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
