version: '2'
volumes:
  mongodb-volume:
    driver: 'local'
services:
  app:
    container_name: app
    image: pb10005/mondai-gallery
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb-volume:/data/db
    ports:
      - '27017:27017'
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/app/client
    stdin_open: true
    tty: true
